"""Render a Marketing Activation playbook to a PowerPoint deck.

The playbook is the structured JSON generated by the marketing enrichment
pipeline (budget tiers, channel mix, search themes, Meta audiences, KPIs and
watch-outs). One deck per catchment, themed with the brand colours like the
report deck, and clearly labelled AI-generated for review. Internal only, like
the pipeline that produces it.
"""

from __future__ import annotations

import io

from pptx import Presentation
from pptx.util import Inches

from .report_pptx import _GREY, _WHITE, _darken, _footer, _hex, _rect, _text


def render_marketing_pptx(
    playbook: dict,
    heading: str,
    heading_color: str | None = None,
    logo: bytes | None = None,
    accent: str | None = None,
) -> bytes:
    """Render the marketing activation deck for one catchment's playbook."""
    navy = _hex(heading_color)
    accent_rgb = _hex(accent, "C9A24B")
    theme = {"navy": navy, "accent": accent_rgb}
    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)
    blank = prs.slide_layouts[6]

    _cover(prs.slides.add_slide(blank), playbook, heading, theme, logo)
    for build in (
        lambda s: _budget_and_channels(s, playbook, theme),
        lambda s: _search_and_meta(s, playbook, theme),
        lambda s: _kpis_and_watchouts(s, playbook, theme),
    ):
        slide = prs.slides.add_slide(blank)
        build(slide)
        _footer(slide, theme, logo, on_dark=False)

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()


def _cover(slide, playbook: dict, heading: str, theme: dict, logo) -> None:  # noqa: ANN001
    _rect(slide, 0, 0, Inches(13.333), Inches(7.5), theme["navy"])
    _text(
        slide,
        Inches(0.8),
        Inches(1.6),
        Inches(11.7),
        Inches(0.5),
        [("MARKETING ACTIVATION", 14, theme["accent"], True, False)],
    )
    _text(
        slide,
        Inches(0.8),
        Inches(2.2),
        Inches(11.7),
        Inches(1.4),
        [(heading, 40, _WHITE, True, False)],
        shrink=True,
    )
    if playbook.get("summary"):
        _text(
            slide,
            Inches(0.8),
            Inches(3.9),
            Inches(11.0),
            Inches(1.8),
            [(playbook["summary"], 16, _WHITE, False, False)],
            shrink=True,
        )
    model = playbook.get("model")
    _text(
        slide,
        Inches(0.8),
        Inches(6.4),
        Inches(11.7),
        Inches(0.6),
        [
            (
                "Internal use only. AI-generated"
                + (f" by {model}" if model else "")
                + " from the catchment's Battlecard data. Review before use.",
                11,
                theme["accent"],
                False,
                True,
            )
        ],
    )


def _heading_row(slide, title: str, theme: dict) -> None:  # noqa: ANN001
    _text(
        slide,
        Inches(0.6),
        Inches(0.45),
        Inches(12.1),
        Inches(0.7),
        [(title, 24, theme["navy"], True, False)],
    )


def _card(slide, left, top, width, height, title: str, lines: list, theme: dict) -> None:  # noqa: ANN001
    """A titled panel of small text lines, the deck's repeating unit."""
    _rect(slide, left, top, width, height, _darken(_WHITE, 0.97))
    _text(
        slide,
        left + Inches(0.15),
        top + Inches(0.12),
        width - Inches(0.3),
        Inches(0.35),
        [(title, 12, theme["navy"], True, False)],
    )
    if lines:
        _text(
            slide,
            left + Inches(0.15),
            top + Inches(0.5),
            width - Inches(0.3),
            height - Inches(0.65),
            lines,
            shrink=True,
        )


def _budget_and_channels(slide, playbook: dict, theme: dict) -> None:  # noqa: ANN001
    _heading_row(slide, "Budget split and channel mix", theme)
    tiers = playbook.get("budgetTiers") or []
    mixes = {m.get("tier"): m for m in (playbook.get("channelMix") or [])}
    top = Inches(1.3)
    height = Inches(5.6 / max(len(tiers), 1)) if tiers else Inches(5.6)
    for i, t in enumerate(tiers[:4]):
        share = t.get("sharePct")
        title = f"{t.get('tier', 'Tier')}" + (
            f"  ·  {share}% of budget" if share is not None else ""
        )
        lines: list = []
        if t.get("audience"):
            lines.append((t["audience"], 11, theme["navy"], False, False))
        if t.get("rationale"):
            lines.append((t["rationale"], 10, _GREY, False, False))
        mix = mixes.get(t.get("tier"))
        if mix and mix.get("channels"):
            channels = "   •   ".join(
                f"{c.get('channel', '')} {c.get('sharePct')}%"
                if c.get("sharePct") is not None
                else str(c.get("channel", ""))
                for c in mix["channels"]
            )
            lines.append((channels, 10, theme["accent"], True, False))
        _card(
            slide,
            Inches(0.6),
            top + i * height,
            Inches(12.1),
            height - Inches(0.15),
            title,
            lines,
            theme,
        )


def _search_and_meta(slide, playbook: dict, theme: dict) -> None:  # noqa: ANN001
    _heading_row(slide, "Google Search themes and Meta audiences", theme)
    themes = (playbook.get("searchThemes") or [])[:4]
    metas = (playbook.get("metaAudiences") or [])[:4]
    col_w = Inches(5.95)
    for col, (label, items) in enumerate(
        (("GOOGLE SEARCH", themes), ("META (FACEBOOK AND INSTAGRAM)", metas))
    ):
        left = Inches(0.6) + col * (col_w + Inches(0.2))
        _text(
            slide,
            left,
            Inches(1.25),
            col_w,
            Inches(0.35),
            [(label, 11, _GREY, True, False)],
        )
        height = Inches(5.2 / max(len(items), 1)) if items else Inches(5.2)
        for i, item in enumerate(items):
            if label.startswith("GOOGLE"):
                title = item.get("theme", "Theme")
                lines = []
                if item.get("intent"):
                    lines.append((item["intent"], 10, _GREY, False, False))
                if item.get("exampleKeywords"):
                    lines.append(
                        (
                            "  ·  ".join(item["exampleKeywords"][:6]),
                            10,
                            theme["navy"],
                            False,
                            True,
                        )
                    )
            else:
                title = item.get("name", "Audience")
                lines = []
                if item.get("definition"):
                    lines.append((item["definition"], 10, _GREY, False, False))
                if item.get("creativeAngle"):
                    lines.append(
                        (item["creativeAngle"], 10, theme["navy"], False, True)
                    )
            _card(
                slide,
                left,
                Inches(1.7) + i * height,
                col_w,
                height - Inches(0.15),
                title,
                lines,
                theme,
            )


def _kpis_and_watchouts(slide, playbook: dict, theme: dict) -> None:  # noqa: ANN001
    _heading_row(slide, "KPIs and watch-outs", theme)
    kpis = (playbook.get("kpis") or [])[:6]
    col_w = Inches(3.95)
    for i, k in enumerate(kpis):
        lines = [(k.get("target", ""), 16, theme["navy"], True, False)]
        if k.get("why"):
            lines.append((k["why"], 10, _GREY, False, False))
        _card(
            slide,
            Inches(0.6) + (i % 3) * (col_w + Inches(0.15)),
            Inches(1.3) + (i // 3) * Inches(1.75),
            col_w,
            Inches(1.6),
            k.get("metric", "KPI"),
            lines,
            theme,
        )
    watch = playbook.get("watchOuts") or []
    if watch:
        _card(
            slide,
            Inches(0.6),
            Inches(5.0),
            Inches(12.1),
            Inches(1.9),
            "WATCH-OUTS",
            [(f"•  {w}", 11, _GREY, False, False) for w in watch[:6]],
            theme,
        )
